# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CMC_C <- function(nDim_input, M_input, Margin_input, Y_input = 1L, item_used_input = 0L) {
    .Call(`_CMC_CMC_C`, nDim_input, M_input, Margin_input, Y_input, item_used_input)
}

rcpp_hello_world <- function() {
    .Call(`_CMC_rcpp_hello_world`)
}

