# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CMC <- function(nDim_input, M_input, Margin_input, Y_input = 1L, item_used_input = 0L) {
    .Call(`_scNorm3D_CMC`, nDim_input, M_input, Margin_input, Y_input, item_used_input)
}

